-- =====================================================
-- STOCK HEALTH & REORDER INTELLIGENCE
-- =====================================================

-- 1️⃣ Database & Schemas
CREATE DATABASE IF NOT EXISTS STOCK_HEALTH_DB;
CREATE SCHEMA IF NOT EXISTS STOCK_HEALTH_DB.RAW;
CREATE SCHEMA IF NOT EXISTS STOCK_HEALTH_DB.ANALYTICS;

-- =====================================================
-- 2️⃣ Raw Table
CREATE OR REPLACE TABLE STOCK_HEALTH_DB.RAW.DAILY_STOCK (
    DATE DATE,
    LOCATION STRING,
    ITEM STRING,
    OPENING_STOCK INT,
    RECEIVED INT,
    ISSUED INT,
    CLOSING_STOCK INT,
    LEAD_TIME_DAYS INT
);

-- =====================================================
-- 3️⃣ Core Metrics View
CREATE OR REPLACE VIEW STOCK_HEALTH_DB.ANALYTICS.STOCK_METRICS AS
SELECT
    DATE,
    LOCATION,
    ITEM,
    CLOSING_STOCK,
    LEAD_TIME_DAYS,
    AVG(ISSUED) OVER (
        PARTITION BY LOCATION, ITEM
        ORDER BY DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS AVG_DAILY_CONSUMPTION,
    CASE
        WHEN AVG(ISSUED) OVER (
            PARTITION BY LOCATION, ITEM
            ORDER BY DATE
            ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
        ) = 0 THEN NULL
        ELSE CLOSING_STOCK /
             AVG(ISSUED) OVER (
                PARTITION BY LOCATION, ITEM
                ORDER BY DATE
                ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
             )
    END AS DAYS_OF_COVER
FROM STOCK_HEALTH_DB.RAW.DAILY_STOCK;

-- =====================================================
-- 4️⃣ Gold View (Risk + Reorder)
CREATE OR REPLACE VIEW STOCK_HEALTH_DB.ANALYTICS.STOCK_GOLD AS
SELECT
    *,
    CASE
        WHEN DAYS_OF_COVER < 3 THEN 'CRITICAL'
        WHEN DAYS_OF_COVER < 7 THEN 'HIGH'
        WHEN DAYS_OF_COVER < 14 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_LEVEL,
    GREATEST(
        CEIL((LEAD_TIME_DAYS + 3) * AVG_DAILY_CONSUMPTION - CLOSING_STOCK),
        0
    ) AS REORDER_QUANTITY
FROM STOCK_HEALTH_DB.ANALYTICS.STOCK_METRICS;

-- =====================================================
-- 5️⃣ Summary Statistics View
CREATE OR REPLACE VIEW STOCK_HEALTH_DB.ANALYTICS.STOCK_SUMMARY AS
SELECT
    COUNT(DISTINCT LOCATION) AS TOTAL_LOCATIONS,
    COUNT(DISTINCT ITEM) AS TOTAL_ITEMS,

    SUM(CASE WHEN RISK_LEVEL = 'CRITICAL' THEN 1 ELSE 0 END) AS CRITICAL_ITEMS,
    SUM(CASE WHEN RISK_LEVEL = 'HIGH' THEN 1 ELSE 0 END) AS HIGH_RISK_ITEMS,
    SUM(CASE WHEN RISK_LEVEL = 'MEDIUM' THEN 1 ELSE 0 END) AS MEDIUM_RISK_ITEMS,
    SUM(CASE WHEN RISK_LEVEL = 'LOW' THEN 1 ELSE 0 END) AS LOW_RISK_ITEMS

FROM STOCK_HEALTH_DB.ANALYTICS.STOCK_GOLD;
